language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "node"

cache:
  directories:
    - node_modules
    - bower_components

before_install:

install:
  - du -sh ./node_modules ./bower_components/ || true
  - npm config set spin false
  - npm config set loglevel http
  - npm install -g gulp
  - npm install -g bower
  - npm install -g coveralls
  - npm install
  - bower install

script:
  - gulp build:dist
  - gulp test

after_success:
  - coveralls
